[build]
  base = "client"
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[dev]
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
